include: package:flutter_lints/flutter.yaml

analyzer:
  strong-mode:
    implicit-casts: false
    implicit-dynamic: false
  exclude:
    - '**.g.dart'
    - 'lib/generated/**'

linter:
  rules:
    prefer_const_constructor: false
    prefer_const_declarations: false
    avoid_print: false
    prefer_single_quotes: true
    always_use_package_imports: true
