name: todo_list
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.16.2 <3.0.0"


dependencies:
  flutter:
    sdk: flutter
  intl: ^0.17.0
  flutter_localizations:
    sdk: flutter
  adaptive_theme: ^2.3.1
  get_it: ^7.2.0
  hive_flutter: ^1.1.0
  dartz: ^0.10.1
  equatable: ^2.0.3
  flutter_bloc: ^8.0.1
  provider: ^6.0.3
  flutter_keyboard_visibility: ^5.3.0
  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  hive_generator: ^1.1.3
  build_runner: ^2.1.11
  flutter_lints: ^1.0.0

flutter:
  uses-material-design: true

flutter_intl:
  enabled: true
